### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Lelelo1** [hightower70/MagCal#1]
Hey!

I tried this compensation algorithm with the magnetometer readings of my navigation app. This is the update method I have:

```
void update()
{
    var r = Reading;
    r = MagneticCompensation.Compensate(r);
    Algorithm.Update( /* (Madgwick) */
        (float)r.gX, (float)r.gY, (float)r.gZ,
        (float)r.aX, (float)r.aY, (float)r.aZ,
        (float)r.mX, (float)r.mY, (float)r.mZ);
}
```
where m is the magnetometer readings.

As the magnetometer values are given in this form to the [madgwick](https://github.com/xioTechnologies/Fusion/issues/8) sensor fusion algorithm I did not understand what the after-following matrices does - and if they are necessary?

![combinedBiasVector](https://user-images.githubusercontent.com/42244983/85879812-49acbe80-b7db-11ea-9d22-7869318f86c6.png)

**Comment by Lelelo1** [comment]
I have found this sketch:
![sketch](https://user-images.githubusercontent.com/42244983/85919624-3c401480-b86d-11ea-8427-17fc568e2ff3.png)

from https://diydrones.com/profiles/blogs/advanced-hard-and-soft-iron-magnetometer-calibration-for-dummies

So I assume the difference of the reading vector and the combined bias vector should be multiplied by either the `A_1` matrix or the `A` matrix

```
Matrix<double> A_1 = SQ * hm / hmb;

Console.WriteLine("A-1 matrix:");
Console.WriteLine(A_1.ToString());

// Calculate A to permit comparison with MagCal 
Matrix<double> A = A_1.Inverse();

Console.WriteLine("A matrix:");
Console.WriteLine(A.ToString());
```

**Comment by hightower70** [comment]
Hi,

the equation on the picture is correct. The transformation matrix is the A_1 matrix.

**Comment by Lelelo1** [comment]
```
// Calculate combined bias
B[0] = -B[0];     // x-axis combined bias
B[1] = -B[1];     // y-axis combined bias
B[2] = -B[2];     // z-axis combined bias
```

<strike>As the bias vector is produced by 10 rows of data. Can it be used with any of the data rows in the set (with `A_1` matrix) to produce a calibrated vector?</strike>

<strike>In my case I have access to live sensor data. Do you think it would work to take the 10 most recent sensor updates and expect a good result? Can I use one row of data?</strike>

I have read more about magnetometer calibration, and some more source code examples. As I understand it a few values (which should be as accurate as possible) is taked to construct the sphere.
So MagCal is about constructing the A_1 matrix based off sphere/ellipsoid calculation. So it is not about implementing calibration on live data fully - it has to be done all well. (My use case being mobile app development)

**Comment by Lelelo1** [comment]
Can I generate a sphere with earth's magnetic field vector of world magnetic model? See: https://www.ngdc.noaa.gov/geomag/WMM/calculators.shtml - you can use Single Point Calculator and give latitude longitude of gps. It should give the ideal sphere based off the actual earth's magnetic field.

**Comment by Lelelo1** [comment]
I managed to set it up correctly. With list storing recent values, calibrating the newest value. It had almost the same calibration accuracy as the default ios calibration.
